version: '3'
volumes:
  k3s-server: {}
  k3s-agent: {}
services:
  server:
    hostname: k3s-master-1
    restart: always
    image: "gcr.io/its-artifact-commons/k3s:${K3S_VERSION}"
    command:
    - server
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=secret
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
      - .:/output
      - ./addons/initial-secrets.yaml:/var/lib/rancher/k3s/server/manifests/initial-secrets.yaml
      - k3s-server:/var/lib/rancher/k3s
    ports:
    - 6443:6443

  agent:
    hostname: k3s-worker-1
    restart: always
    image: "gcr.io/its-artifact-commons/k3s:${K3S_VERSION}"
    command:
    - agent
    tmpfs:
    - /run
    - /var/run
    privileged: true
    volumes:
      - k3s-agent:/etc/rancher/node
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=secret

  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"      

  prometheus:
    environment:
      - DUMMY=001
      - DEVICE_ID=${DEVICE_ID}
      - REMOTE_PROM_USER=${REMOTE_PROM_USER}
      - REMOTE_PROM_PASSWORD=${REMOTE_PROM_PASSWORD}
      - REMOTE_PROM_URL=${REMOTE_PROM_URL}
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --enable-feature=expand-external-labels
    container_name: prometheus
    image: prom/prometheus:v2.43.0
    user: root
    restart: always
    volumes:
      - ${BASEDIR}/00-configs/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ${WIP_DIR}/prometheus:/prometheus
